-- 핀포즈 9 개. 부위 3 × 레벨 3 이다.
--
-- target_pose_id 를 명시한다. IDENTITY 에 맡기지 않는 것은 이 값이 도메인 3 곳에 값으로
-- 퍼지기 때문이다 — course.course_template.target_pose_id(자연키), course.course.target_pose_id,
-- course.stamp.target_pose_id. 도메인 간 FK 가 없어 어긋나도 DB 가 막지 않는다.
-- screening.body_part 가 코드를 PK 로 쓴 것과 같은 이유다.
--
-- level 은 부위 안에서의 난이도이고 자세 도전 현황 그리드의 왼쪽부터 1·2·3 이다
-- (Figma 와이어프레임 「자세 도전 현황」). 회원이 코스를 고를 때 (부위, 레벨)로 고르므로
-- 표시 순서와 난이도가 같은 값이다.
--
-- image_asset_key 는 URL 이 아니라 프론트 정적 자산의 키다. `target-pose/{영문 slug}` 규칙은
-- docs/frontend-integration.md 의 예시 응답(`target-pose/camel`·`target-pose/bridge`)을 따른다.
--
-- ymove_slug 는 전부 NULL 이다. YMove 연동이 자세별로 확정되는 대로 UPDATE changeset 을
-- 새로 쌓아 채운다 (docs/plan-8-catalog-도메인.md §0-3). UNIQUE 는 NULL 을 여러 개 허용한다.
INSERT INTO catalog.target_pose (target_pose_id, name, body_part_code, level, image_asset_key)
VALUES (1, '업독', 'BACK', 1, 'target-pose/upward-facing-dog'),
       (2, '낙타자세', 'BACK', 2, 'target-pose/camel'),
       (3, '휠', 'BACK', 3, 'target-pose/wheel'),
       (4, '반 보트', 'ABDOMEN', 1, 'target-pose/half-boat'),
       (5, '보트자세', 'ABDOMEN', 2, 'target-pose/boat'),
       (6, '사이드 플랭크', 'ABDOMEN', 3, 'target-pose/side-plank'),
       (7, '브릿지', 'PELVIS', 1, 'target-pose/bridge'),
       (8, '말라사나', 'PELVIS', 2, 'target-pose/malasana'),
       (9, '파이어로그', 'PELVIS', 3, 'target-pose/fire-log');

-- GENERATED BY DEFAULT AS IDENTITY 는 명시 INSERT 를 허용하지만 시퀀스를 따라 올리지 않는다.
-- 리셋하지 않으면 훗날 id 없이 넣는 첫 행이 1 을 받아 PK 충돌로 터진다.
ALTER TABLE catalog.target_pose
    ALTER COLUMN target_pose_id RESTART WITH 100;
