package team.aligner.member.repository.jdbc

import org.springframework.data.annotation.Id
import org.springframework.data.relational.core.mapping.Table
import java.time.Instant

/**
 * schema 를 명시하지 않으면 public 을 친다 (docs/architecture.md §6).
 *
 * memberId 가 null 이면 Spring Data JDBC 가 insert 로 판단한다.
 * DDL 의 GENERATED BY DEFAULT AS IDENTITY 가 값을 채운다.
 *
 * experienceLevel 을 enum 이 아니라 String 으로 둔다. DDL 의 CHECK 이 값 집합을 강제하고,
 * 변환은 모델 경계(toModel)에서 한다 — screening 의 perceivedDifficulty 와 같은 형태다.
 */
@Table(schema = "member", name = "member")
internal data class MemberEntity(
    @Id
    val memberId: Long?,
    val kakaoId: String?,
    val nickname: String?,
    val profileImageUrl: String?,
    val heightCm: Int?,
    val weightKg: Int?,
    val experienceLevel: String?,
    val reinforcementBodyPartCode: String?,
    val reinforcementLevel: Int?,
    val withdrawnAt: Instant?,
    val createdAt: Instant,
    val updatedAt: Instant,
)
