package team.aligner.member.repository.jdbc

import org.springframework.data.annotation.Id
import org.springframework.data.relational.core.mapping.Table
import java.time.Instant

/**
 * schema 를 명시하지 않으면 public 을 친다 (docs/architecture.md §6).
 *
 * memberId 가 null 이면 Spring Data JDBC 가 insert 로 판단한다.
 * DDL 의 GENERATED BY DEFAULT AS IDENTITY 가 값을 채운다.
 */
@Table(schema = "member", name = "member")
internal data class MemberEntity(
    @Id
    val memberId: Long?,
    val kakaoId: String,
    val nickname: String?,
    val profileImageUrl: String?,
    val createdAt: Instant,
    val updatedAt: Instant,
)
