http:
  routers:
    dozzle:
      rule: PathPrefix(`/logs`)
      entryPoints:
        - web
      service: dozzle
      priority: 100
    api:
      rule: PathPrefix(`/`)
      entryPoints:
        - web
      service: api
      priority: 1
  services:
    dozzle:
      loadBalancer:
        servers:
          - url: http://dozzle:8080
    api:
      loadBalancer:
        servers:
          - url: http://api:8080
