-- 코스 템플릿. 목표 자세 하나에 코스 하나다.
--
-- **하나의 핀포즈가 곧 하나의 코스다.** 회원이 고른 (강화 부위, 난이도)가 곧
-- catalog.target_pose 의 (body_part_code, level)이고, 그 자세의 템플릿으로 코스를 처방한다.
-- 그래서 template 의 자연키가 target_pose_id 다.
--
-- cause_code 가 없다. 초판 설계는 원인별 템플릿이었지만 처방 입력이 (부위, 레벨)로 바뀌었다.
-- 원인은 여전히 쓰이되 "회원이 고른 부위가 실제 진단 결과에 있는가" 를 검증하는 데만 쓴다
-- (docs/domains.md §2). 검증은 처방 시점의 판단이라 마스터에 남길 값이 아니다.
--
-- unlock_required_target_pose_id 도 없다. 회원이 난이도를 직접 고르므로 해금 사다리가 없다.
CREATE TABLE course.course_template (
    template_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_pose_id          BIGINT       NOT NULL,
    name                    VARCHAR(100) NOT NULL,
    recommendation_reason   TEXT,
    CONSTRAINT uk_course_template_target_pose UNIQUE (target_pose_id)
);

COMMENT ON TABLE course.course_template IS '목표 자세 하나에 대응하는 코스 마스터. 감수 seed 다';
COMMENT ON COLUMN course.course_template.target_pose_id IS 'catalog.target_pose 의 값이지만 도메인 간 FK 는 걸지 않는다';
COMMENT ON COLUMN course.course_template.name IS '"낙타자세 정복하기" 처럼 코스 개요 상단에 그리는 이름';
COMMENT ON COLUMN course.course_template.recommendation_reason IS '"코스 추천 이유" 문구. 감수 대상이라 서버가 조립하지 않는다';
