-- 템플릿의 스텝. 코스 개요의 번호 매겨진 행 하나다.
CREATE TABLE course.template_step (
    template_step_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id      BIGINT   NOT NULL,
    step_order       SMALLINT NOT NULL,
    CONSTRAINT fk_template_step_template FOREIGN KEY (template_id)
        REFERENCES course.course_template (template_id),
    CONSTRAINT uk_template_step_order UNIQUE (template_id, step_order),
    CONSTRAINT ck_template_step_order CHECK (step_order > 0)
);

COMMENT ON TABLE course.template_step IS '템플릿 스텝. course 내부 FK 다 — 금지된 것은 도메인 간 FK 다';
