-- 스텝에 편성된 운동.
--
-- 서로게이트 키에 UNIQUE 를 건다. (template_step_id, display_order)를 PK 로 쓰면 재감수로
-- 순서가 바뀔 때마다 식별자가 흔들린다 (catalog.exercise_voice_cue 와 같은 판단).
--
-- duration_seconds·set_count 는 override 다. 비어 있으면 catalog.exercise 의 기본값을 쓴다.
-- 같은 준비 동작이 레벨별로 1분 30초·2분·2분 30초를 갖는 사례가 콘텐츠 정본에 있다
-- (docs/domains.md §7-1).
CREATE TABLE course.template_step_exercise (
    template_step_exercise_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_step_id          BIGINT   NOT NULL,
    exercise_id               BIGINT   NOT NULL,
    display_order             SMALLINT NOT NULL,
    duration_seconds          INT,
    set_count                 SMALLINT,
    CONSTRAINT fk_template_step_exercise_step FOREIGN KEY (template_step_id)
        REFERENCES course.template_step (template_step_id),
    CONSTRAINT uk_template_step_exercise_order UNIQUE (template_step_id, display_order),
    CONSTRAINT ck_template_step_exercise_order CHECK (display_order > 0),
    CONSTRAINT ck_template_step_exercise_duration CHECK (duration_seconds > 0),
    CONSTRAINT ck_template_step_exercise_set_count CHECK (set_count > 0)
);

COMMENT ON COLUMN course.template_step_exercise.exercise_id IS 'catalog.exercise 의 값이지만 도메인 간 FK 는 걸지 않는다';
COMMENT ON COLUMN course.template_step_exercise.duration_seconds IS 'NULL 이면 catalog.exercise.default_duration_seconds 를 쓴다';
COMMENT ON COLUMN course.template_step_exercise.set_count IS 'NULL 이면 catalog.exercise.default_set_count 를 쓴다';
