-- 회원에게 처방된 코스. 애그리거트 루트다.
--
-- scheduled_on 이 없다. 초판 설계는 홈이 "오늘의 코스 / 내일의 코스" 를 보여준다는 전제로
-- 코스를 일자 단위로 뒀는데, 확정된 화면에 내일의 코스가 없다. **진행 중인 코스가 곧 오늘의
-- 코스다** (docs/domains.md §4-4).
--
-- (member_id, target_pose_id) 가 유니크다. 하나의 핀포즈가 하나의 코스이므로 같은 회원이
-- 같은 자세의 코스를 두 개 가질 수 없다. **처방 멱등성이 여기서 나온다** — 같은 요청이
-- 재시도돼도 새 코스가 생기지 않고 이미 있는 코스가 돌아간다.
--
-- cause_code 는 처방 시점에 검증에 쓴 원인의 스냅샷이다. 나중에 다시 진단해서 원인이 바뀌어도
-- 이 코스가 왜 처방됐는지는 남아야 한다.
CREATE TABLE course.course (
    course_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id          BIGINT      NOT NULL,
    template_id        BIGINT      NOT NULL,
    target_pose_id     BIGINT      NOT NULL,
    cause_code         VARCHAR(40),
    status             VARCHAR(20) NOT NULL,
    created_at         TIMESTAMPTZ NOT NULL,
    completed_at       TIMESTAMPTZ,
    CONSTRAINT fk_course_template FOREIGN KEY (template_id)
        REFERENCES course.course_template (template_id),
    CONSTRAINT uk_course_member_target_pose UNIQUE (member_id, target_pose_id),
    CONSTRAINT ck_course_status CHECK (status IN ('IN_PROGRESS', 'COMPLETED')),
    -- 완료 상태와 완료 시각이 따로 놀지 않게 한다.
    CONSTRAINT ck_course_completed_at CHECK ((status = 'COMPLETED') = (completed_at IS NOT NULL))
);

-- 홈이 "진행 중인 코스" 하나를 집고, 도전 현황이 회원의 코스 전체를 훑는다.
CREATE INDEX ix_course_member ON course.course (member_id);

COMMENT ON TABLE course.course IS '회원별 처방 코스. 목표 자세 하나에 코스 하나다';
COMMENT ON COLUMN course.course.member_id IS 'member.member 의 값이지만 도메인 간 FK 는 걸지 않는다';
COMMENT ON COLUMN course.course.cause_code IS '처방 시점 원인의 스냅샷. 재진단으로 원인이 바뀌어도 남는다';
COMMENT ON COLUMN course.course.status IS 'IN_PROGRESS 는 도전 중, COMPLETED 는 완성이다';
