-- 회원 코스의 스텝. 템플릿 스텝을 처방 시점에 복사한 것이다.
--
-- **복사하는 이유는 진행 상태가 회원별이기 때문**이고, 템플릿 seed 가 나중에 바뀌어도 이미
-- 처방된 코스의 구성이 흔들리면 안 되기 때문이다.
--
-- 진행도는 이 테이블의 COMPLETED 개수 / 전체 개수다. 자세 도전 현황의 "3 / 4" 가 이 값이다
-- (docs/domains.md §7-8).
CREATE TABLE course.course_step (
    course_step_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id      BIGINT      NOT NULL,
    step_order     SMALLINT    NOT NULL,
    status         VARCHAR(20) NOT NULL,
    completed_at   TIMESTAMPTZ,
    CONSTRAINT fk_course_step_course FOREIGN KEY (course_id)
        REFERENCES course.course (course_id),
    CONSTRAINT uk_course_step_order UNIQUE (course_id, step_order),
    CONSTRAINT ck_course_step_order CHECK (step_order > 0),
    CONSTRAINT ck_course_step_status CHECK (status IN ('NOT_STARTED', 'COMPLETED')),
    CONSTRAINT ck_course_step_completed_at CHECK ((status = 'COMPLETED') = (completed_at IS NOT NULL))
);

COMMENT ON TABLE course.course_step IS '회원 코스의 스텝. 완료 개수가 곧 진행도다';
