-- 스텝에 편성된 운동. 템플릿에서 복사되며 override 값이 함께 굳는다.
CREATE TABLE course.course_step_exercise (
    course_step_exercise_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_step_id          BIGINT   NOT NULL,
    exercise_id             BIGINT   NOT NULL,
    display_order           SMALLINT NOT NULL,
    duration_seconds        INT,
    set_count               SMALLINT,
    CONSTRAINT fk_course_step_exercise_step FOREIGN KEY (course_step_id)
        REFERENCES course.course_step (course_step_id),
    CONSTRAINT uk_course_step_exercise_order UNIQUE (course_step_id, display_order),
    CONSTRAINT ck_course_step_exercise_order CHECK (display_order > 0),
    CONSTRAINT ck_course_step_exercise_duration CHECK (duration_seconds > 0),
    CONSTRAINT ck_course_step_exercise_set_count CHECK (set_count > 0)
);

COMMENT ON COLUMN course.course_step_exercise.exercise_id IS 'catalog.exercise 의 값이지만 도메인 간 FK 는 걸지 않는다';
COMMENT ON COLUMN course.course_step_exercise.duration_seconds IS 'NULL 이면 catalog.exercise 의 기본값을 쓴다';

-- source 컬럼이 없다. 보강 편성이 없으므로 이 운동이 어디서 왔는지 구분할 이유가 없다
-- (docs/domains.md §4-3).
