-- 도장. 목표 자세를 완수하면 붙는다.
--
-- 판정은 코스의 모든 스텝 완료다. 자세 포인트 체크가 없으므로 다른 근거가 없다
-- (docs/domains.md §7-8).
--
-- (member_id, target_pose_id) 유니크가 중복 부여를 막는다. 세션 완료 push 가 재시도돼도
-- 도장이 두 번 붙지 않는다.
CREATE TABLE course.stamp (
    stamp_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id      BIGINT      NOT NULL,
    target_pose_id BIGINT      NOT NULL,
    course_id      BIGINT      NOT NULL,
    acquired_at    TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_stamp_course FOREIGN KEY (course_id) REFERENCES course.course (course_id),
    CONSTRAINT uk_stamp_member_target_pose UNIQUE (member_id, target_pose_id)
);

COMMENT ON TABLE course.stamp IS '완수한 목표 자세. 프로필의 "완수한 자세 목록" 이 읽는다';
