-- 세션 1 회. 코스 스텝 하나를 수행한 기록이다.
--
-- **완수 판정이 여기 없다.** training 은 "무슨 일이 있었나" 만 기록하고 진행도·도장 판단은
-- 전부 course 가 한다 (docs/domains.md §2). 이 테이블에 도장이나 진행도 컬럼이 생기면
-- 잘못 나눈 것이다.
--
-- course_id·member_id 는 값 컬럼이고 도메인 간 FK 가 없다 (§6).
CREATE TABLE training.session (
    session_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id    BIGINT      NOT NULL,
    course_id    BIGINT      NOT NULL,
    step_order   SMALLINT    NOT NULL,
    status       VARCHAR(20) NOT NULL,
    started_at   TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    CONSTRAINT ck_session_status CHECK (status IN ('IN_PROGRESS', 'COMPLETED')),
    CONSTRAINT ck_session_step_order CHECK (step_order > 0),
    -- 완료 상태와 완료 시각이 따로 놀지 않게 한다 (course.course 와 같은 형태).
    CONSTRAINT ck_session_completed_at CHECK ((status = 'COMPLETED') = (completed_at IS NOT NULL))
);

-- 세션 복구는 식별자로 집지만, 회원의 세션 이력을 훑는 조회가 뒤따른다.
CREATE INDEX ix_session_member ON training.session (member_id, started_at DESC);

COMMENT ON TABLE training.session IS '세션 1 회. 코스 스텝 하나의 수행 기록이다';
COMMENT ON COLUMN training.session.course_id IS 'course.course 의 값이지만 도메인 간 FK 는 걸지 않는다';
COMMENT ON COLUMN training.session.step_order IS '수행한 코스 스텝의 순서. 완료 시 이 값으로 course 에 push 한다';
