-- 세션 안에서 운동 하나를 어떻게 수행했는가.
--
-- 세션 시작 시 코스 스텝 구성을 복사해 completed = false 로 만들어 두고, 완료 요청이 값을
-- 채운다. 복사해 두는 이유는 세션 중 코스가 바뀌어도 이 세션이 무엇을 수행했는지가
-- 흔들리면 안 되기 때문이다.
--
-- course_step_exercise_id 를 함께 두는 것은 exercise_id 만으로는 같은 운동이 한 스텝에 두 번
-- 편성된 경우를 가릴 수 없어서다. exercise_id 도 남기는 것은 catalog 조회에 코스를 다시 읽지
-- 않기 위해서다.
CREATE TABLE training.session_exercise_record (
    record_id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id                 BIGINT   NOT NULL,
    course_step_exercise_id    BIGINT   NOT NULL,
    exercise_id                BIGINT   NOT NULL,
    display_order              SMALLINT NOT NULL,
    completed                  BOOLEAN  NOT NULL,
    performed_duration_seconds INT,
    CONSTRAINT fk_session_exercise_record_session FOREIGN KEY (session_id)
        REFERENCES training.session (session_id),
    CONSTRAINT uk_session_exercise_record UNIQUE (session_id, course_step_exercise_id),
    CONSTRAINT ck_session_exercise_record_order CHECK (display_order > 0),
    CONSTRAINT ck_session_exercise_record_duration CHECK (performed_duration_seconds >= 0)
);

COMMENT ON TABLE training.session_exercise_record IS '세션 안의 운동 수행 기록';
COMMENT ON COLUMN training.session_exercise_record.course_step_exercise_id IS 'course.course_step_exercise 의 값이지만 도메인 간 FK 는 걸지 않는다';
COMMENT ON COLUMN training.session_exercise_record.performed_duration_seconds IS '실제 수행 시간. 수행하지 않았으면 NULL 이다';
