-- IF NOT EXISTS 를 쓰지 않는다. 적용 여부는 Liquibase 가 추적하므로, 정의가 다른 테이블이
-- 이미 있으면 조용히 넘어가는 대신 실패하는 편이 낫다.
CREATE TABLE member.member (
    member_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kakao_id          VARCHAR(64)  NOT NULL,
    nickname          VARCHAR(50),
    profile_image_url VARCHAR(500),
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_member_kakao_id UNIQUE (kakao_id)
);

COMMENT ON TABLE member.member IS '회원. 카카오 식별자로 가입한다';
COMMENT ON COLUMN member.member.kakao_id IS '카카오 회원번호. 같은 계정이 두 번 가입되지 않게 유니크다';
COMMENT ON COLUMN member.member.nickname IS '카카오 프로필 미동의 시 비어 있다. 기본값을 만들어 넣지 않는다';
