-- IF NOT EXISTS 를 쓰지 않는다. 적용 여부는 Liquibase 가 추적하므로, 정의가 다른 테이블이
-- 이미 있으면 조용히 넘어가는 대신 실패하는 편이 낫다.
--
-- created_at / updated_at 이 없다. catalog 는 쓰기가 없는 감수 seed 도메인이라 감사 시각이
-- 생길 자리가 없다 (docs/domains.md §4-3). 콘텐츠 운영 API 가 생기면 그때 ADD COLUMN 한다.
CREATE TABLE catalog.exercise (
    exercise_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ymove_slug               VARCHAR(120),
    name                     VARCHAR(100)  NOT NULL,
    default_set_count        SMALLINT,
    default_rep_count        SMALLINT,
    default_duration_seconds INT,
    met_value                NUMERIC(4, 2),
    difficulty               VARCHAR(20),
    caution_note             TEXT,
    CONSTRAINT uk_exercise_ymove_slug UNIQUE (ymove_slug),
    CONSTRAINT ck_exercise_default_duration CHECK (default_duration_seconds > 0),
    CONSTRAINT ck_exercise_met_value CHECK (met_value > 0)
);

COMMENT ON TABLE catalog.exercise IS '보강 운동. 코스 스텝으로 재생되는 동작이다. 핀포즈도 여기에 행을 갖는다';
COMMENT ON COLUMN catalog.exercise.ymove_slug IS 'YMove 연결 고리. 좌우 분리 자세 취급이 미정이라 NULL 을 허용한다 (docs/domains.md §7-6). UNIQUE 는 NULL 을 여러 개 허용한다';
COMMENT ON COLUMN catalog.exercise.name IS 'YMove title 을 우리 표현으로 덮는 override';
COMMENT ON COLUMN catalog.exercise.default_duration_seconds IS '기본 수행 시간. course.course_step_exercise 가 비어 있을 때 쓴다';
COMMENT ON COLUMN catalog.exercise.met_value IS '칼로리 계산 입력. kcal 은 회원 몸무게의 함수라 저장하지 않고 조회 시 계산한다';
COMMENT ON COLUMN catalog.exercise.difficulty IS '우리가 감수로 부여한다. YMove 는 요가 전량을 beginner 로 태깅해 변별력이 없다. 값 집합이 미정이라 CHECK 을 걸지 않았다';
COMMENT ON COLUMN catalog.exercise.caution_note IS '운동 가이드의 주의사항 탭 문구. 금기 조건도 이 문장 안에 담는다';
