-- 목표 자세(핀포즈). 부위별 레벨 1 → 2 → 3 선형이고 분기하지 않는다 (docs/domains.md §7-2).
--
-- 같은 ymove_slug 가 catalog.exercise 에도 존재한다. 핀포즈는 코스 스텝으로 재생되면서
-- 동시에 코스의 목표라 두 역할을 겸하기 때문이다 (§4-3). exercise_id 를 참조하지 않는 것은
-- target_pose_id 가 screening·course 에 값 컬럼으로 퍼져 있어 독립적으로 안정돼야 해서다.
CREATE TABLE catalog.target_pose (
    target_pose_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ymove_slug      VARCHAR(120),
    name            VARCHAR(100) NOT NULL,
    image_asset_key VARCHAR(120),
    body_part_code  VARCHAR(40)  NOT NULL,
    level           SMALLINT     NOT NULL,
    CONSTRAINT uk_target_pose_ymove_slug UNIQUE (ymove_slug),
    CONSTRAINT ck_target_pose_level CHECK (level > 0)
);

-- 온보딩 자세 그리드가 부위로 걸러 조회한다.
CREATE INDEX ix_target_pose_body_part_code ON catalog.target_pose (body_part_code);

COMMENT ON TABLE catalog.target_pose IS '목표 자세(핀포즈). 진행도와 사다리 해금의 단위다';
COMMENT ON COLUMN catalog.target_pose.image_asset_key IS 'URL 이 아니라 안정된 키다. 이미지 파일은 프론트가 정적으로 갖는다';
COMMENT ON COLUMN catalog.target_pose.body_part_code IS 'screening.body_part 의 값이지만 도메인 간 FK 는 걸지 않는다';
COMMENT ON COLUMN catalog.target_pose.level IS '부위 안에서의 단계. 우리가 감수로 부여한다';
