-- 목표 자세가 쓰는 근육.
--
-- 서로게이트 PK 에 UNIQUE 를 건다. 콘텐츠 정본에 한 자세에서 같은 근육이 두 역할을 갖는
-- 사례가 없어 role 을 키에서 뺐지만, 후굴에서 척추기립근이 수축과 신장을 겸하는 식의 감수
-- 결과가 나올 수 있다. 그때 PK 를 바꾸는 것보다 UNIQUE 만 재정의하는 편이 가볍다
-- (docs/domains.md §4-3).
--
-- catalog 안의 FK 는 건다. docs/architecture.md §6 이 금지한 것은 도메인 간 FK 다.
CREATE TABLE catalog.pose_muscle (
    pose_muscle_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_pose_id BIGINT      NOT NULL,
    muscle_code    VARCHAR(40) NOT NULL,
    role           VARCHAR(20) NOT NULL,
    display_order  SMALLINT    NOT NULL,
    CONSTRAINT fk_pose_muscle_target_pose FOREIGN KEY (target_pose_id)
        REFERENCES catalog.target_pose (target_pose_id),
    CONSTRAINT fk_pose_muscle_muscle FOREIGN KEY (muscle_code)
        REFERENCES catalog.muscle (muscle_code),
    CONSTRAINT uk_pose_muscle UNIQUE (target_pose_id, muscle_code),
    CONSTRAINT ck_pose_muscle_role CHECK (role IN ('STRETCH', 'STRENGTHEN'))
);

CREATE INDEX ix_pose_muscle_target_pose_id ON catalog.pose_muscle (target_pose_id);

COMMENT ON TABLE catalog.pose_muscle IS '목표 자세가 쓰는 근육';
COMMENT ON COLUMN catalog.pose_muscle.role IS 'STRETCH 는 늘리는 근육, STRENGTHEN 은 쓰는 근육. 콘텐츠 정본의 "(신장)" 표기가 전자다';
COMMENT ON COLUMN catalog.pose_muscle.display_order IS '운동 가이드에 그리는 순서';
