-- 보강 운동이 쓰는 근육. 키 구성 근거는 004 와 같다.
CREATE TABLE catalog.exercise_muscle (
    exercise_muscle_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercise_id        BIGINT      NOT NULL,
    muscle_code        VARCHAR(40) NOT NULL,
    role               VARCHAR(20) NOT NULL,
    display_order      SMALLINT    NOT NULL,
    CONSTRAINT fk_exercise_muscle_exercise FOREIGN KEY (exercise_id)
        REFERENCES catalog.exercise (exercise_id),
    CONSTRAINT fk_exercise_muscle_muscle FOREIGN KEY (muscle_code)
        REFERENCES catalog.muscle (muscle_code),
    CONSTRAINT uk_exercise_muscle UNIQUE (exercise_id, muscle_code),
    CONSTRAINT ck_exercise_muscle_role CHECK (role IN ('STRETCH', 'STRENGTHEN'))
);

CREATE INDEX ix_exercise_muscle_exercise_id ON catalog.exercise_muscle (exercise_id);

COMMENT ON TABLE catalog.exercise_muscle IS '보강 운동이 쓰는 근육';
COMMENT ON COLUMN catalog.exercise_muscle.role IS 'STRETCH 는 늘리는 근육, STRENGTHEN 은 쓰는 근육';
