-- 세션 재생 중 나가는 음성 큐. 한글 번역본이며 catalog 가 소유한다.
--
-- YMove 의 instructions 는 영어라 그대로 쓸 수 없다. 번역 전처리 결과를 여기 담는다
-- (docs/domains.md §4-3-1).
--
-- 컬럼 하나가 아니라 별도 테이블인 이유는 타임코드 때문이다. offset_seconds 가 확정되기
-- 전까지는 NULL 이고 재생은 display_order 순차로 한다. 확정되면 UPDATE changeset 으로 값만
-- 채우므로 스키마가 바뀌지 않는다. TEXT 컬럼으로 뒀다면 테이블 전환에 데이터 변환
-- changeset 이 필요했다 (§4-3).
CREATE TABLE catalog.exercise_voice_cue (
    cue_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercise_id    BIGINT   NOT NULL,
    display_order  SMALLINT NOT NULL,
    offset_seconds INT,
    content        TEXT     NOT NULL,
    CONSTRAINT fk_exercise_voice_cue_exercise FOREIGN KEY (exercise_id)
        REFERENCES catalog.exercise (exercise_id),
    CONSTRAINT uk_exercise_voice_cue UNIQUE (exercise_id, display_order),
    CONSTRAINT ck_exercise_voice_cue_offset CHECK (offset_seconds >= 0)
);

CREATE INDEX ix_exercise_voice_cue_exercise_id ON catalog.exercise_voice_cue (exercise_id);

COMMENT ON TABLE catalog.exercise_voice_cue IS '음성 큐잉 대본. YMove 영어 원문을 번역한 우리 자산이다';
COMMENT ON COLUMN catalog.exercise_voice_cue.offset_seconds IS '타임코드. 미확정이라 NULL 을 허용한다. NULL 이면 display_order 순차 재생이다';
COMMENT ON COLUMN catalog.exercise_voice_cue.content IS '한글 번역본. 감수 대상이다';
