-- 세션 재생 중 나가는 음성 큐. 한글 번역본이며 catalog 가 소유한다.
--
-- YMove 의 instructions 는 영어라 그대로 쓸 수 없다. 번역 전처리 결과를 여기 담는다
-- (docs/domains.md §4-3-1).
--
-- 컬럼 하나가 아니라 별도 테이블인 이유는 타임코드 때문이다. 타임코드가 확정되기 전까지는
-- 두 offset 이 NULL 이고 재생은 display_order 순차로 한다. 확정되면 UPDATE changeset 으로
-- 값만 채우므로 스키마가 바뀌지 않는다. TEXT 컬럼으로 뒀다면 테이블 전환에 데이터 변환
-- changeset 이 필요했다 (§4-3).
--
-- 큐를 순간이 아니라 구간으로 둔다. 핀포즈가 "40 초 × 3" 처럼 유지 구간을 갖고 세션 플레이어가
-- 카운트다운을 그리므로, 큐가 언제 끝나는지가 화면에 필요하다. end 를 다음 큐의 start 로
-- 추론하면 큐 사이에 침묵 구간을 둘 수 없고 마지막 큐의 끝을 알 수 없다.
CREATE TABLE catalog.exercise_voice_cue (
    cue_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercise_id          BIGINT   NOT NULL,
    display_order        SMALLINT NOT NULL,
    start_offset_seconds INT,
    end_offset_seconds   INT,
    content              TEXT     NOT NULL,
    CONSTRAINT fk_exercise_voice_cue_exercise FOREIGN KEY (exercise_id)
        REFERENCES catalog.exercise (exercise_id),
    CONSTRAINT uk_exercise_voice_cue UNIQUE (exercise_id, display_order),
    CONSTRAINT ck_exercise_voice_cue_start CHECK (start_offset_seconds >= 0),
    -- end 만 있고 start 가 없는 상태를 막는다. 둘 다 NULL 이거나 순서가 맞아야 한다.
    CONSTRAINT ck_exercise_voice_cue_range CHECK (
        end_offset_seconds IS NULL
            OR (start_offset_seconds IS NOT NULL AND end_offset_seconds > start_offset_seconds)
    )
);

CREATE INDEX ix_exercise_voice_cue_exercise_id ON catalog.exercise_voice_cue (exercise_id);

COMMENT ON TABLE catalog.exercise_voice_cue IS '음성 큐잉 대본. YMove 영어 원문을 번역한 우리 자산이다';
COMMENT ON COLUMN catalog.exercise_voice_cue.start_offset_seconds IS '큐 시작 타임코드. 미확정이라 NULL 을 허용한다. NULL 이면 display_order 순차 재생이다';
COMMENT ON COLUMN catalog.exercise_voice_cue.end_offset_seconds IS '큐 종료 타임코드. 유지 구간이 없는 큐는 NULL 이다';
COMMENT ON COLUMN catalog.exercise_voice_cue.content IS '한글 번역본. 감수 대상이다';
