-- 운동 가이드의 부위 탭마다 붙는 「핵심 동작」 문구.
--
-- **키가 (운동, 부위)다.** 근육 단위가 아니다 — 탭 하나에 근육이 여럿 칠해지므로
-- exercise_muscle 에 문구 컬럼을 두면 같은 문구가 근육 수만큼 중복되고 서로 어긋날 수 있다.
--
-- exercise_voice_cue 와 자리가 다르다. 저쪽은 재생 타임라인 대본이라 start_offset_seconds 를
-- 갖고, 이쪽은 재생 전 정적 설명이다. 문구를 지시사항에서 뽑아 쓰더라도 저장은 독립적으로
-- 한다 — 대본이 감수로 바뀔 때 핵심 동작이 같이 흔들리면 안 된다.
--
-- body_part_code 에 CHECK 을 걸지 않는다. screening 소유 어휘라 catalog 가 값 집합을 못박지
-- 않는다 (catalog.muscle.body_part_code 와 같은 판단, docs/architecture.md §6).
--
-- catalog 안의 FK 는 건다. 금지된 것은 도메인 간 FK 다.
CREATE TABLE catalog.exercise_body_part_guide (
    guide_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercise_id    BIGINT      NOT NULL,
    body_part_code VARCHAR(40) NOT NULL,
    content        TEXT        NOT NULL,
    display_order  SMALLINT    NOT NULL,
    CONSTRAINT fk_exercise_body_part_guide_exercise FOREIGN KEY (exercise_id)
        REFERENCES catalog.exercise (exercise_id),
    CONSTRAINT uk_exercise_body_part_guide UNIQUE (exercise_id, body_part_code)
);

-- exercise_id 단독 인덱스를 두지 않는다. uk_exercise_body_part_guide 가 선행 컬럼 조회를
-- 그대로 커버한다 (ddl/004 와 같다).

COMMENT ON TABLE catalog.exercise_body_part_guide IS '운동 가이드 부위 탭의 핵심 동작 문구';
COMMENT ON COLUMN catalog.exercise_body_part_guide.body_part_code IS 'screening.body_part 의 값이지만 도메인 간 FK 는 걸지 않는다';
COMMENT ON COLUMN catalog.exercise_body_part_guide.content IS '한 문장짜리 핵심 동작. 감수 대상이다';
COMMENT ON COLUMN catalog.exercise_body_part_guide.display_order IS '부위 탭 표시 순서. 작을수록 먼저다';
