package team.aligner.screening.repository.jdbc

import org.springframework.data.annotation.Id
import org.springframework.data.relational.core.mapping.MappedCollection
import org.springframework.data.relational.core.mapping.Table
import java.time.Instant

/**
 * schema 를 명시하지 않으면 public 을 친다 (docs/architecture.md §6).
 *
 * resultId 가 null 이면 Spring Data JDBC 가 insert 로 판단한다.
 * DDL 의 GENERATED BY DEFAULT AS IDENTITY 가 값을 채운다.
 *
 * 자식 둘을 @MappedCollection 으로 매단다. 애그리거트 저장이 한 번에 끝나야
 * "응답은 있는데 원인이 없는 진단" 이 생기지 않는다 (docs/architecture.md §4).
 */
@Table(schema = "screening", name = "screening_result")
internal data class ScreeningResultEntity(
    @Id
    val resultId: Long?,
    val memberId: Long,
    val perceivedBodyPartCode: String,
    val createdAt: Instant,
    @MappedCollection(idColumn = "result_id")
    val answers: Set<ScreeningAnswerEntity>,
    @MappedCollection(idColumn = "result_id")
    val causes: Set<ScreeningCauseEntity>,
)

@Table(schema = "screening", name = "screening_answer")
internal data class ScreeningAnswerEntity(
    @Id
    val answerId: Long?,
    val targetPoseId: Long,
    // enum 이 아니라 String 이다. DDL 의 CHECK 이 값 집합을 강제하고, 변환은 모델 경계에서 한다.
    val perceivedDifficulty: String,
)

@Table(schema = "screening", name = "screening_cause")
internal data class ScreeningCauseEntity(
    @Id
    val screeningCauseId: Long?,
    val causeCode: String,
    val rank: Int,
    val score: Int,
)
