-- (자세, 체감) → 원인 분기표. screening 의 핵심 seed 다.
--
-- weight 를 두는 것은 자세를 최대 8 개까지 고르기 때문이다. 원인마다 점수가 쌓이고 그 합으로
-- 순위를 매긴다. **집계 방식을 코드가 아니라 이 값으로 조절한다** — 감수 결과가 바뀌어도
-- changeset 만 새로 쌓으면 되고 판별 코드는 그대로다 (docs/domains.md §4-2).
--
-- target_pose_id 는 catalog 의 값이지만 FK 를 걸지 않는다. 도메인 간 참조라 값 컬럼이다(§6).
-- screening 은 어떤 도메인도 의존하지 않는다.
CREATE TABLE screening.cause_rule (
    rule_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_pose_id        BIGINT      NOT NULL,
    perceived_difficulty  VARCHAR(10) NOT NULL,
    cause_code            VARCHAR(40) NOT NULL,
    weight                SMALLINT    NOT NULL,
    -- 같은 (자세, 체감) 이 같은 원인에 두 번 가중치를 주면 점수가 조용히 부풀어 순위가 뒤틀린다.
    CONSTRAINT uk_cause_rule_pose_difficulty_cause
        UNIQUE (target_pose_id, perceived_difficulty, cause_code),
    -- 응답의 같은 이름 컬럼과 값 집합이 같아야 조인이 성립한다.
    CONSTRAINT ck_cause_rule_perceived_difficulty
        CHECK (perceived_difficulty IN ('EASY', 'HARD')),
    CONSTRAINT ck_cause_rule_weight CHECK (weight > 0),
    CONSTRAINT fk_cause_rule_cause FOREIGN KEY (cause_code)
        REFERENCES screening.cause (cause_code)
);

-- 판별이 회원 응답의 자세 식별자로 규칙을 긁어온다.
CREATE INDEX ix_cause_rule_target_pose_id ON screening.cause_rule (target_pose_id);

COMMENT ON TABLE screening.cause_rule IS '(자세, 체감) → 원인 분기표. 전량 seed 이고 감수 대상이다';
COMMENT ON COLUMN screening.cause_rule.target_pose_id IS 'catalog.target_pose 의 값이지만 도메인 간 FK 는 걸지 않는다';
COMMENT ON COLUMN screening.cause_rule.weight IS '이 규칙이 원인에 더하는 점수. 집계 조절을 코드가 아니라 이 값으로 한다';
