-- 회원이 고른 자세 체감. 애그리거트의 자식이다.
--
-- 온보딩은 핀포즈 그리드에서 쉬웠던 자세와 어려웠던 자세를 각각 최대 4 개 고른다.
-- 설문 문항이 없으므로 screening_question·screening_option 을 만들지 않는다 (§4-2).
CREATE TABLE screening.screening_answer (
    answer_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    result_id            BIGINT      NOT NULL,
    target_pose_id       BIGINT      NOT NULL,
    perceived_difficulty VARCHAR(10) NOT NULL,
    -- 점수를 합산해 순위를 매기므로 응답이 중복되면 그대로 순위가 뒤틀린다. 같은 자세를
    -- EASY 와 HARD 로 같이 제출하는 모순도 이 하나로 같이 막힌다 — 그래서
    -- perceived_difficulty 를 키에서 뺐다 (docs/domains.md §4-2).
    CONSTRAINT uk_screening_answer_result_pose UNIQUE (result_id, target_pose_id),
    CONSTRAINT ck_screening_answer_perceived_difficulty
        CHECK (perceived_difficulty IN ('EASY', 'HARD')),
    CONSTRAINT fk_screening_answer_result FOREIGN KEY (result_id)
        REFERENCES screening.screening_result (result_id) ON DELETE CASCADE
);

COMMENT ON TABLE screening.screening_answer IS '회원이 고른 자세와 그 체감. 난이도별 최대 4 개는 애그리거트가 검증한다';
COMMENT ON COLUMN screening.screening_answer.target_pose_id IS 'catalog.target_pose 의 값이지만 도메인 간 FK 는 걸지 않는다';
COMMENT ON COLUMN screening.screening_answer.perceived_difficulty IS 'EASY 는 쉬웠던 자세, HARD 는 어려웠던 자세다';
