-- 판별된 원인. 애그리거트의 자식이고 결과 화면이 순위로 나열한다.
--
-- 원인이 복수다. 진단 결과가 원인 부위를 순위로 보여주므로 result 하나에 여러 행이 달린다
-- (docs/domains.md §4-2).
--
-- score 는 매칭된 cause_rule.weight 의 합이다. 값을 저장해 두는 것은 seed 의 weight 가
-- 나중에 바뀌어도 그때 내린 진단 결과가 재계산되지 않게 하기 위해서다.
CREATE TABLE screening.screening_cause (
    screening_cause_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    result_id          BIGINT      NOT NULL,
    cause_code         VARCHAR(40) NOT NULL,
    rank               SMALLINT    NOT NULL,
    score              INT         NOT NULL,
    -- 한 진단에서 같은 원인이 두 번 나오거나 같은 순위가 두 번 나오면 화면이 그릴 수 없다.
    CONSTRAINT uk_screening_cause_result_cause UNIQUE (result_id, cause_code),
    CONSTRAINT uk_screening_cause_result_rank UNIQUE (result_id, rank),
    CONSTRAINT ck_screening_cause_rank CHECK (rank > 0),
    CONSTRAINT ck_screening_cause_score CHECK (score > 0),
    CONSTRAINT fk_screening_cause_result FOREIGN KEY (result_id)
        REFERENCES screening.screening_result (result_id) ON DELETE CASCADE,
    CONSTRAINT fk_screening_cause_cause FOREIGN KEY (cause_code)
        REFERENCES screening.cause (cause_code)
);

COMMENT ON TABLE screening.screening_cause IS '판별된 원인. course 가 처방에 쓰는 값이다';
COMMENT ON COLUMN screening.screening_cause.rank IS '표시 순서. 1 부터 시작하고 점수 내림차순이다';
COMMENT ON COLUMN screening.screening_cause.score IS '매칭된 cause_rule.weight 합계. 진단 시점 값을 그대로 보관한다';
